// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/lgxju/gogretago/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockModelRepository is an autogenerated mock type for the ModelRepository type
type MockModelRepository struct {
	mock.Mock
}

type MockModelRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModelRepository) EXPECT() *MockModelRepository_Expecter {
	return &MockModelRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, data
func (_m *MockModelRepository) Create(ctx context.Context, data entities.CreateModelData) (*entities.VehicleModel, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.VehicleModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.CreateModelData) (*entities.VehicleModel, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.CreateModelData) *entities.VehicleModel); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.VehicleModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.CreateModelData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockModelRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data entities.CreateModelData
func (_e *MockModelRepository_Expecter) Create(ctx interface{}, data interface{}) *MockModelRepository_Create_Call {
	return &MockModelRepository_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *MockModelRepository_Create_Call) Run(run func(ctx context.Context, data entities.CreateModelData)) *MockModelRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.CreateModelData))
	})
	return _c
}

func (_c *MockModelRepository_Create_Call) Return(_a0 *entities.VehicleModel, _a1 error) *MockModelRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModelRepository_Create_Call) RunAndReturn(run func(context.Context, entities.CreateModelData) (*entities.VehicleModel, error)) *MockModelRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockModelRepository) FindAll(ctx context.Context) ([]entities.VehicleModel, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entities.VehicleModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.VehicleModel, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.VehicleModel); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.VehicleModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockModelRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockModelRepository_Expecter) FindAll(ctx interface{}) *MockModelRepository_FindAll_Call {
	return &MockModelRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockModelRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockModelRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockModelRepository_FindAll_Call) Return(_a0 []entities.VehicleModel, _a1 error) *MockModelRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModelRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]entities.VehicleModel, error)) *MockModelRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockModelRepository) FindByID(ctx context.Context, id string) (*entities.VehicleModel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.VehicleModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.VehicleModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.VehicleModel); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.VehicleModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockModelRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockModelRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockModelRepository_FindByID_Call {
	return &MockModelRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockModelRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockModelRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockModelRepository_FindByID_Call) Return(_a0 *entities.VehicleModel, _a1 error) *MockModelRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModelRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*entities.VehicleModel, error)) *MockModelRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByNameAndBrand provides a mock function with given fields: ctx, name, brandRefID
func (_m *MockModelRepository) FindByNameAndBrand(ctx context.Context, name string, brandRefID int64) (*entities.VehicleModel, error) {
	ret := _m.Called(ctx, name, brandRefID)

	if len(ret) == 0 {
		panic("no return value specified for FindByNameAndBrand")
	}

	var r0 *entities.VehicleModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (*entities.VehicleModel, error)); ok {
		return rf(ctx, name, brandRefID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) *entities.VehicleModel); ok {
		r0 = rf(ctx, name, brandRefID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.VehicleModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, name, brandRefID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelRepository_FindByNameAndBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByNameAndBrand'
type MockModelRepository_FindByNameAndBrand_Call struct {
	*mock.Call
}

// FindByNameAndBrand is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - brandRefID int64
func (_e *MockModelRepository_Expecter) FindByNameAndBrand(ctx interface{}, name interface{}, brandRefID interface{}) *MockModelRepository_FindByNameAndBrand_Call {
	return &MockModelRepository_FindByNameAndBrand_Call{Call: _e.mock.On("FindByNameAndBrand", ctx, name, brandRefID)}
}

func (_c *MockModelRepository_FindByNameAndBrand_Call) Run(run func(ctx context.Context, name string, brandRefID int64)) *MockModelRepository_FindByNameAndBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockModelRepository_FindByNameAndBrand_Call) Return(_a0 *entities.VehicleModel, _a1 error) *MockModelRepository_FindByNameAndBrand_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModelRepository_FindByNameAndBrand_Call) RunAndReturn(run func(context.Context, string, int64) (*entities.VehicleModel, error)) *MockModelRepository_FindByNameAndBrand_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockModelRepository creates a new instance of MockModelRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModelRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModelRepository {
	mock := &MockModelRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
