// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/lgxju/gogretago/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockColorRepository is an autogenerated mock type for the ColorRepository type
type MockColorRepository struct {
	mock.Mock
}

type MockColorRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockColorRepository) EXPECT() *MockColorRepository_Expecter {
	return &MockColorRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, data
func (_m *MockColorRepository) Create(ctx context.Context, data entities.CreateColorData) (*entities.Color, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.Color
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.CreateColorData) (*entities.Color, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.CreateColorData) *entities.Color); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Color)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.CreateColorData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockColorRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockColorRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data entities.CreateColorData
func (_e *MockColorRepository_Expecter) Create(ctx interface{}, data interface{}) *MockColorRepository_Create_Call {
	return &MockColorRepository_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *MockColorRepository_Create_Call) Run(run func(ctx context.Context, data entities.CreateColorData)) *MockColorRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.CreateColorData))
	})
	return _c
}

func (_c *MockColorRepository_Create_Call) Return(_a0 *entities.Color, _a1 error) *MockColorRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockColorRepository_Create_Call) RunAndReturn(run func(context.Context, entities.CreateColorData) (*entities.Color, error)) *MockColorRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockColorRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockColorRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockColorRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockColorRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockColorRepository_Delete_Call {
	return &MockColorRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockColorRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockColorRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockColorRepository_Delete_Call) Return(_a0 error) *MockColorRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockColorRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockColorRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, skip, take
func (_m *MockColorRepository) FindAll(ctx context.Context, skip int, take int) ([]entities.Color, int, error) {
	ret := _m.Called(ctx, skip, take)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entities.Color
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]entities.Color, int, error)); ok {
		return rf(ctx, skip, take)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []entities.Color); ok {
		r0 = rf(ctx, skip, take)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Color)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, skip, take)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, skip, take)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockColorRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockColorRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - skip int
//   - take int
func (_e *MockColorRepository_Expecter) FindAll(ctx interface{}, skip interface{}, take interface{}) *MockColorRepository_FindAll_Call {
	return &MockColorRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, skip, take)}
}

func (_c *MockColorRepository_FindAll_Call) Run(run func(ctx context.Context, skip int, take int)) *MockColorRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockColorRepository_FindAll_Call) Return(_a0 []entities.Color, _a1 int, _a2 error) *MockColorRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockColorRepository_FindAll_Call) RunAndReturn(run func(context.Context, int, int) ([]entities.Color, int, error)) *MockColorRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockColorRepository) FindByID(ctx context.Context, id string) (*entities.Color, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Color
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Color, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Color); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Color)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockColorRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockColorRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockColorRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockColorRepository_FindByID_Call {
	return &MockColorRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockColorRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockColorRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockColorRepository_FindByID_Call) Return(_a0 *entities.Color, _a1 error) *MockColorRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockColorRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*entities.Color, error)) *MockColorRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *MockColorRepository) FindByName(ctx context.Context, name string) (*entities.Color, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *entities.Color
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Color, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Color); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Color)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockColorRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockColorRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockColorRepository_Expecter) FindByName(ctx interface{}, name interface{}) *MockColorRepository_FindByName_Call {
	return &MockColorRepository_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockColorRepository_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockColorRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockColorRepository_FindByName_Call) Return(_a0 *entities.Color, _a1 error) *MockColorRepository_FindByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockColorRepository_FindByName_Call) RunAndReturn(run func(context.Context, string) (*entities.Color, error)) *MockColorRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, data
func (_m *MockColorRepository) Update(ctx context.Context, id string, data entities.UpdateColorData) (*entities.Color, error) {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entities.Color
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.UpdateColorData) (*entities.Color, error)); ok {
		return rf(ctx, id, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.UpdateColorData) *entities.Color); ok {
		r0 = rf(ctx, id, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Color)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, entities.UpdateColorData) error); ok {
		r1 = rf(ctx, id, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockColorRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockColorRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - data entities.UpdateColorData
func (_e *MockColorRepository_Expecter) Update(ctx interface{}, id interface{}, data interface{}) *MockColorRepository_Update_Call {
	return &MockColorRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, data)}
}

func (_c *MockColorRepository_Update_Call) Run(run func(ctx context.Context, id string, data entities.UpdateColorData)) *MockColorRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entities.UpdateColorData))
	})
	return _c
}

func (_c *MockColorRepository_Update_Call) Return(_a0 *entities.Color, _a1 error) *MockColorRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockColorRepository_Update_Call) RunAndReturn(run func(context.Context, string, entities.UpdateColorData) (*entities.Color, error)) *MockColorRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockColorRepository creates a new instance of MockColorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockColorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockColorRepository {
	mock := &MockColorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
