// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/lgxju/gogretago/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockInscriptionRepository is an autogenerated mock type for the InscriptionRepository type
type MockInscriptionRepository struct {
	mock.Mock
}

type MockInscriptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInscriptionRepository) EXPECT() *MockInscriptionRepository_Expecter {
	return &MockInscriptionRepository_Expecter{mock: &_m.Mock}
}

// CountByTripRefID provides a mock function with given fields: ctx, tripRefID
func (_m *MockInscriptionRepository) CountByTripRefID(ctx context.Context, tripRefID int64) (int, error) {
	ret := _m.Called(ctx, tripRefID)

	if len(ret) == 0 {
		panic("no return value specified for CountByTripRefID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int, error)); ok {
		return rf(ctx, tripRefID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int); ok {
		r0 = rf(ctx, tripRefID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, tripRefID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInscriptionRepository_CountByTripRefID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByTripRefID'
type MockInscriptionRepository_CountByTripRefID_Call struct {
	*mock.Call
}

// CountByTripRefID is a helper method to define mock.On call
//   - ctx context.Context
//   - tripRefID int64
func (_e *MockInscriptionRepository_Expecter) CountByTripRefID(ctx interface{}, tripRefID interface{}) *MockInscriptionRepository_CountByTripRefID_Call {
	return &MockInscriptionRepository_CountByTripRefID_Call{Call: _e.mock.On("CountByTripRefID", ctx, tripRefID)}
}

func (_c *MockInscriptionRepository_CountByTripRefID_Call) Run(run func(ctx context.Context, tripRefID int64)) *MockInscriptionRepository_CountByTripRefID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockInscriptionRepository_CountByTripRefID_Call) Return(_a0 int, _a1 error) *MockInscriptionRepository_CountByTripRefID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInscriptionRepository_CountByTripRefID_Call) RunAndReturn(run func(context.Context, int64) (int, error)) *MockInscriptionRepository_CountByTripRefID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, data
func (_m *MockInscriptionRepository) Create(ctx context.Context, data entities.CreateInscriptionData) (*entities.Inscription, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.Inscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.CreateInscriptionData) (*entities.Inscription, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.CreateInscriptionData) *entities.Inscription); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Inscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.CreateInscriptionData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInscriptionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockInscriptionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data entities.CreateInscriptionData
func (_e *MockInscriptionRepository_Expecter) Create(ctx interface{}, data interface{}) *MockInscriptionRepository_Create_Call {
	return &MockInscriptionRepository_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *MockInscriptionRepository_Create_Call) Run(run func(ctx context.Context, data entities.CreateInscriptionData)) *MockInscriptionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.CreateInscriptionData))
	})
	return _c
}

func (_c *MockInscriptionRepository_Create_Call) Return(_a0 *entities.Inscription, _a1 error) *MockInscriptionRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInscriptionRepository_Create_Call) RunAndReturn(run func(context.Context, entities.CreateInscriptionData) (*entities.Inscription, error)) *MockInscriptionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockInscriptionRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInscriptionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockInscriptionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockInscriptionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockInscriptionRepository_Delete_Call {
	return &MockInscriptionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockInscriptionRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockInscriptionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInscriptionRepository_Delete_Call) Return(_a0 error) *MockInscriptionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInscriptionRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockInscriptionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByUserAndTrip provides a mock function with given fields: ctx, userRefID, tripRefID
func (_m *MockInscriptionRepository) ExistsByUserAndTrip(ctx context.Context, userRefID int64, tripRefID int64) (bool, error) {
	ret := _m.Called(ctx, userRefID, tripRefID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByUserAndTrip")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (bool, error)); ok {
		return rf(ctx, userRefID, tripRefID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) bool); ok {
		r0 = rf(ctx, userRefID, tripRefID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, userRefID, tripRefID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInscriptionRepository_ExistsByUserAndTrip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByUserAndTrip'
type MockInscriptionRepository_ExistsByUserAndTrip_Call struct {
	*mock.Call
}

// ExistsByUserAndTrip is a helper method to define mock.On call
//   - ctx context.Context
//   - userRefID int64
//   - tripRefID int64
func (_e *MockInscriptionRepository_Expecter) ExistsByUserAndTrip(ctx interface{}, userRefID interface{}, tripRefID interface{}) *MockInscriptionRepository_ExistsByUserAndTrip_Call {
	return &MockInscriptionRepository_ExistsByUserAndTrip_Call{Call: _e.mock.On("ExistsByUserAndTrip", ctx, userRefID, tripRefID)}
}

func (_c *MockInscriptionRepository_ExistsByUserAndTrip_Call) Run(run func(ctx context.Context, userRefID int64, tripRefID int64)) *MockInscriptionRepository_ExistsByUserAndTrip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockInscriptionRepository_ExistsByUserAndTrip_Call) Return(_a0 bool, _a1 error) *MockInscriptionRepository_ExistsByUserAndTrip_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInscriptionRepository_ExistsByUserAndTrip_Call) RunAndReturn(run func(context.Context, int64, int64) (bool, error)) *MockInscriptionRepository_ExistsByUserAndTrip_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, skip, take
func (_m *MockInscriptionRepository) FindAll(ctx context.Context, skip int, take int) ([]entities.Inscription, int, error) {
	ret := _m.Called(ctx, skip, take)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entities.Inscription
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]entities.Inscription, int, error)); ok {
		return rf(ctx, skip, take)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []entities.Inscription); ok {
		r0 = rf(ctx, skip, take)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Inscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, skip, take)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, skip, take)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockInscriptionRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockInscriptionRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - skip int
//   - take int
func (_e *MockInscriptionRepository_Expecter) FindAll(ctx interface{}, skip interface{}, take interface{}) *MockInscriptionRepository_FindAll_Call {
	return &MockInscriptionRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, skip, take)}
}

func (_c *MockInscriptionRepository_FindAll_Call) Run(run func(ctx context.Context, skip int, take int)) *MockInscriptionRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockInscriptionRepository_FindAll_Call) Return(_a0 []entities.Inscription, _a1 int, _a2 error) *MockInscriptionRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockInscriptionRepository_FindAll_Call) RunAndReturn(run func(context.Context, int, int) ([]entities.Inscription, int, error)) *MockInscriptionRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockInscriptionRepository) FindByID(ctx context.Context, id string) (*entities.Inscription, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Inscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Inscription, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Inscription); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Inscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInscriptionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockInscriptionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockInscriptionRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockInscriptionRepository_FindByID_Call {
	return &MockInscriptionRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockInscriptionRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockInscriptionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInscriptionRepository_FindByID_Call) Return(_a0 *entities.Inscription, _a1 error) *MockInscriptionRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInscriptionRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*entities.Inscription, error)) *MockInscriptionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDAndUserID provides a mock function with given fields: ctx, id, userID
func (_m *MockInscriptionRepository) FindByIDAndUserID(ctx context.Context, id string, userID string) (*entities.Inscription, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDAndUserID")
	}

	var r0 *entities.Inscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entities.Inscription, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entities.Inscription); ok {
		r0 = rf(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Inscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInscriptionRepository_FindByIDAndUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDAndUserID'
type MockInscriptionRepository_FindByIDAndUserID_Call struct {
	*mock.Call
}

// FindByIDAndUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockInscriptionRepository_Expecter) FindByIDAndUserID(ctx interface{}, id interface{}, userID interface{}) *MockInscriptionRepository_FindByIDAndUserID_Call {
	return &MockInscriptionRepository_FindByIDAndUserID_Call{Call: _e.mock.On("FindByIDAndUserID", ctx, id, userID)}
}

func (_c *MockInscriptionRepository_FindByIDAndUserID_Call) Run(run func(ctx context.Context, id string, userID string)) *MockInscriptionRepository_FindByIDAndUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockInscriptionRepository_FindByIDAndUserID_Call) Return(_a0 *entities.Inscription, _a1 error) *MockInscriptionRepository_FindByIDAndUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInscriptionRepository_FindByIDAndUserID_Call) RunAndReturn(run func(context.Context, string, string) (*entities.Inscription, error)) *MockInscriptionRepository_FindByIDAndUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTripID provides a mock function with given fields: ctx, tripID
func (_m *MockInscriptionRepository) FindByTripID(ctx context.Context, tripID string) ([]entities.Inscription, error) {
	ret := _m.Called(ctx, tripID)

	if len(ret) == 0 {
		panic("no return value specified for FindByTripID")
	}

	var r0 []entities.Inscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entities.Inscription, error)); ok {
		return rf(ctx, tripID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entities.Inscription); ok {
		r0 = rf(ctx, tripID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Inscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tripID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInscriptionRepository_FindByTripID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTripID'
type MockInscriptionRepository_FindByTripID_Call struct {
	*mock.Call
}

// FindByTripID is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
func (_e *MockInscriptionRepository_Expecter) FindByTripID(ctx interface{}, tripID interface{}) *MockInscriptionRepository_FindByTripID_Call {
	return &MockInscriptionRepository_FindByTripID_Call{Call: _e.mock.On("FindByTripID", ctx, tripID)}
}

func (_c *MockInscriptionRepository_FindByTripID_Call) Run(run func(ctx context.Context, tripID string)) *MockInscriptionRepository_FindByTripID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInscriptionRepository_FindByTripID_Call) Return(_a0 []entities.Inscription, _a1 error) *MockInscriptionRepository_FindByTripID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInscriptionRepository_FindByTripID_Call) RunAndReturn(run func(context.Context, string) ([]entities.Inscription, error)) *MockInscriptionRepository_FindByTripID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *MockInscriptionRepository) FindByUserID(ctx context.Context, userID string) ([]entities.Inscription, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []entities.Inscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entities.Inscription, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entities.Inscription); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Inscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInscriptionRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockInscriptionRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockInscriptionRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockInscriptionRepository_FindByUserID_Call {
	return &MockInscriptionRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockInscriptionRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockInscriptionRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInscriptionRepository_FindByUserID_Call) Return(_a0 []entities.Inscription, _a1 error) *MockInscriptionRepository_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInscriptionRepository_FindByUserID_Call) RunAndReturn(run func(context.Context, string) ([]entities.Inscription, error)) *MockInscriptionRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInscriptionRepository creates a new instance of MockInscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInscriptionRepository {
	mock := &MockInscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
