// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockPasswordService is an autogenerated mock type for the PasswordService type
type MockPasswordService struct {
	mock.Mock
}

type MockPasswordService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordService) EXPECT() *MockPasswordService_Expecter {
	return &MockPasswordService_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function with given fields: password
func (_m *MockPasswordService) Hash(password string) (string, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasswordService_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockPasswordService_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password string
func (_e *MockPasswordService_Expecter) Hash(password interface{}) *MockPasswordService_Hash_Call {
	return &MockPasswordService_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *MockPasswordService_Hash_Call) Run(run func(password string)) *MockPasswordService_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPasswordService_Hash_Call) Return(_a0 string, _a1 error) *MockPasswordService_Hash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasswordService_Hash_Call) RunAndReturn(run func(string) (string, error)) *MockPasswordService_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: password, hash
func (_m *MockPasswordService) Verify(password string, hash string) (bool, error) {
	ret := _m.Called(password, hash)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(password, hash)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(password, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(password, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasswordService_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockPasswordService_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - password string
//   - hash string
func (_e *MockPasswordService_Expecter) Verify(password interface{}, hash interface{}) *MockPasswordService_Verify_Call {
	return &MockPasswordService_Verify_Call{Call: _e.mock.On("Verify", password, hash)}
}

func (_c *MockPasswordService_Verify_Call) Run(run func(password string, hash string)) *MockPasswordService_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockPasswordService_Verify_Call) Return(_a0 bool, _a1 error) *MockPasswordService_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasswordService_Verify_Call) RunAndReturn(run func(string, string) (bool, error)) *MockPasswordService_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordService creates a new instance of MockPasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordService {
	mock := &MockPasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
