// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/lgxju/gogretago/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockCarRepository is an autogenerated mock type for the CarRepository type
type MockCarRepository struct {
	mock.Mock
}

type MockCarRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCarRepository) EXPECT() *MockCarRepository_Expecter {
	return &MockCarRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, data
func (_m *MockCarRepository) Create(ctx context.Context, data entities.CreateCarData) (*entities.Car, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.Car
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.CreateCarData) (*entities.Car, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.CreateCarData) *entities.Car); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Car)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.CreateCarData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCarRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data entities.CreateCarData
func (_e *MockCarRepository_Expecter) Create(ctx interface{}, data interface{}) *MockCarRepository_Create_Call {
	return &MockCarRepository_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *MockCarRepository_Create_Call) Run(run func(ctx context.Context, data entities.CreateCarData)) *MockCarRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.CreateCarData))
	})
	return _c
}

func (_c *MockCarRepository_Create_Call) Return(_a0 *entities.Car, _a1 error) *MockCarRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarRepository_Create_Call) RunAndReturn(run func(context.Context, entities.CreateCarData) (*entities.Car, error)) *MockCarRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCarRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCarRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockCarRepository_Delete_Call {
	return &MockCarRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCarRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockCarRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarRepository_Delete_Call) Return(_a0 error) *MockCarRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockCarRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByLicensePlate provides a mock function with given fields: ctx, licensePlate
func (_m *MockCarRepository) ExistsByLicensePlate(ctx context.Context, licensePlate string) (bool, error) {
	ret := _m.Called(ctx, licensePlate)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByLicensePlate")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, licensePlate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, licensePlate)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, licensePlate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarRepository_ExistsByLicensePlate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByLicensePlate'
type MockCarRepository_ExistsByLicensePlate_Call struct {
	*mock.Call
}

// ExistsByLicensePlate is a helper method to define mock.On call
//   - ctx context.Context
//   - licensePlate string
func (_e *MockCarRepository_Expecter) ExistsByLicensePlate(ctx interface{}, licensePlate interface{}) *MockCarRepository_ExistsByLicensePlate_Call {
	return &MockCarRepository_ExistsByLicensePlate_Call{Call: _e.mock.On("ExistsByLicensePlate", ctx, licensePlate)}
}

func (_c *MockCarRepository_ExistsByLicensePlate_Call) Run(run func(ctx context.Context, licensePlate string)) *MockCarRepository_ExistsByLicensePlate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarRepository_ExistsByLicensePlate_Call) Return(_a0 bool, _a1 error) *MockCarRepository_ExistsByLicensePlate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarRepository_ExistsByLicensePlate_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockCarRepository_ExistsByLicensePlate_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, skip, take
func (_m *MockCarRepository) FindAll(ctx context.Context, skip int, take int) ([]entities.Car, int, error) {
	ret := _m.Called(ctx, skip, take)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entities.Car
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]entities.Car, int, error)); ok {
		return rf(ctx, skip, take)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []entities.Car); ok {
		r0 = rf(ctx, skip, take)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Car)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, skip, take)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, skip, take)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCarRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockCarRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - skip int
//   - take int
func (_e *MockCarRepository_Expecter) FindAll(ctx interface{}, skip interface{}, take interface{}) *MockCarRepository_FindAll_Call {
	return &MockCarRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, skip, take)}
}

func (_c *MockCarRepository_FindAll_Call) Run(run func(ctx context.Context, skip int, take int)) *MockCarRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockCarRepository_FindAll_Call) Return(_a0 []entities.Car, _a1 int, _a2 error) *MockCarRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCarRepository_FindAll_Call) RunAndReturn(run func(context.Context, int, int) ([]entities.Car, int, error)) *MockCarRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockCarRepository) FindByID(ctx context.Context, id string) (*entities.Car, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Car
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Car, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Car); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Car)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCarRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockCarRepository_FindByID_Call {
	return &MockCarRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockCarRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockCarRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarRepository_FindByID_Call) Return(_a0 *entities.Car, _a1 error) *MockCarRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*entities.Car, error)) *MockCarRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, data
func (_m *MockCarRepository) Update(ctx context.Context, id string, data entities.UpdateCarData) (*entities.Car, error) {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entities.Car
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.UpdateCarData) (*entities.Car, error)); ok {
		return rf(ctx, id, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.UpdateCarData) *entities.Car); ok {
		r0 = rf(ctx, id, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Car)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, entities.UpdateCarData) error); ok {
		r1 = rf(ctx, id, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCarRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - data entities.UpdateCarData
func (_e *MockCarRepository_Expecter) Update(ctx interface{}, id interface{}, data interface{}) *MockCarRepository_Update_Call {
	return &MockCarRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, data)}
}

func (_c *MockCarRepository_Update_Call) Run(run func(ctx context.Context, id string, data entities.UpdateCarData)) *MockCarRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entities.UpdateCarData))
	})
	return _c
}

func (_c *MockCarRepository_Update_Call) Return(_a0 *entities.Car, _a1 error) *MockCarRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarRepository_Update_Call) RunAndReturn(run func(context.Context, string, entities.UpdateCarData) (*entities.Car, error)) *MockCarRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCarRepository creates a new instance of MockCarRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCarRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCarRepository {
	mock := &MockCarRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
