// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/lgxju/gogretago/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockCityRepository is an autogenerated mock type for the CityRepository type
type MockCityRepository struct {
	mock.Mock
}

type MockCityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCityRepository) EXPECT() *MockCityRepository_Expecter {
	return &MockCityRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, data
func (_m *MockCityRepository) Create(ctx context.Context, data entities.CreateCityData) (*entities.City, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.City
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.CreateCityData) (*entities.City, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.CreateCityData) *entities.City); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.CreateCityData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCityRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCityRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data entities.CreateCityData
func (_e *MockCityRepository_Expecter) Create(ctx interface{}, data interface{}) *MockCityRepository_Create_Call {
	return &MockCityRepository_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *MockCityRepository_Create_Call) Run(run func(ctx context.Context, data entities.CreateCityData)) *MockCityRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.CreateCityData))
	})
	return _c
}

func (_c *MockCityRepository_Create_Call) Return(_a0 *entities.City, _a1 error) *MockCityRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCityRepository_Create_Call) RunAndReturn(run func(context.Context, entities.CreateCityData) (*entities.City, error)) *MockCityRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCityRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCityRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCityRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCityRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockCityRepository_Delete_Call {
	return &MockCityRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCityRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockCityRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCityRepository_Delete_Call) Return(_a0 error) *MockCityRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCityRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockCityRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, skip, take
func (_m *MockCityRepository) FindAll(ctx context.Context, skip int, take int) ([]entities.City, int, error) {
	ret := _m.Called(ctx, skip, take)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entities.City
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]entities.City, int, error)); ok {
		return rf(ctx, skip, take)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []entities.City); ok {
		r0 = rf(ctx, skip, take)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, skip, take)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, skip, take)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCityRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockCityRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - skip int
//   - take int
func (_e *MockCityRepository_Expecter) FindAll(ctx interface{}, skip interface{}, take interface{}) *MockCityRepository_FindAll_Call {
	return &MockCityRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, skip, take)}
}

func (_c *MockCityRepository_FindAll_Call) Run(run func(ctx context.Context, skip int, take int)) *MockCityRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockCityRepository_FindAll_Call) Return(_a0 []entities.City, _a1 int, _a2 error) *MockCityRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCityRepository_FindAll_Call) RunAndReturn(run func(context.Context, int, int) ([]entities.City, int, error)) *MockCityRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCityName provides a mock function with given fields: ctx, name
func (_m *MockCityRepository) FindByCityName(ctx context.Context, name string) (*entities.City, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByCityName")
	}

	var r0 *entities.City
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.City, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.City); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCityRepository_FindByCityName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCityName'
type MockCityRepository_FindByCityName_Call struct {
	*mock.Call
}

// FindByCityName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockCityRepository_Expecter) FindByCityName(ctx interface{}, name interface{}) *MockCityRepository_FindByCityName_Call {
	return &MockCityRepository_FindByCityName_Call{Call: _e.mock.On("FindByCityName", ctx, name)}
}

func (_c *MockCityRepository_FindByCityName_Call) Run(run func(ctx context.Context, name string)) *MockCityRepository_FindByCityName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCityRepository_FindByCityName_Call) Return(_a0 *entities.City, _a1 error) *MockCityRepository_FindByCityName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCityRepository_FindByCityName_Call) RunAndReturn(run func(context.Context, string) (*entities.City, error)) *MockCityRepository_FindByCityName_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockCityRepository) FindByID(ctx context.Context, id string) (*entities.City, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.City
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.City, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.City); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCityRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCityRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCityRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockCityRepository_FindByID_Call {
	return &MockCityRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockCityRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockCityRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCityRepository_FindByID_Call) Return(_a0 *entities.City, _a1 error) *MockCityRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCityRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*entities.City, error)) *MockCityRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCityRepository creates a new instance of MockCityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCityRepository {
	mock := &MockCityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
