// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/lgxju/gogretago/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockBrandRepository is an autogenerated mock type for the BrandRepository type
type MockBrandRepository struct {
	mock.Mock
}

type MockBrandRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrandRepository) EXPECT() *MockBrandRepository_Expecter {
	return &MockBrandRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, data
func (_m *MockBrandRepository) Create(ctx context.Context, data entities.CreateBrandData) (*entities.Brand, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.Brand
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.CreateBrandData) (*entities.Brand, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.CreateBrandData) *entities.Brand); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Brand)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.CreateBrandData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBrandRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBrandRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data entities.CreateBrandData
func (_e *MockBrandRepository_Expecter) Create(ctx interface{}, data interface{}) *MockBrandRepository_Create_Call {
	return &MockBrandRepository_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *MockBrandRepository_Create_Call) Run(run func(ctx context.Context, data entities.CreateBrandData)) *MockBrandRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.CreateBrandData))
	})
	return _c
}

func (_c *MockBrandRepository_Create_Call) Return(_a0 *entities.Brand, _a1 error) *MockBrandRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBrandRepository_Create_Call) RunAndReturn(run func(context.Context, entities.CreateBrandData) (*entities.Brand, error)) *MockBrandRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockBrandRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBrandRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBrandRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBrandRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockBrandRepository_Delete_Call {
	return &MockBrandRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockBrandRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockBrandRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBrandRepository_Delete_Call) Return(_a0 error) *MockBrandRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBrandRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockBrandRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, skip, take
func (_m *MockBrandRepository) FindAll(ctx context.Context, skip int, take int) ([]entities.Brand, int, error) {
	ret := _m.Called(ctx, skip, take)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entities.Brand
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]entities.Brand, int, error)); ok {
		return rf(ctx, skip, take)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []entities.Brand); ok {
		r0 = rf(ctx, skip, take)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Brand)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, skip, take)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, skip, take)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBrandRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockBrandRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - skip int
//   - take int
func (_e *MockBrandRepository_Expecter) FindAll(ctx interface{}, skip interface{}, take interface{}) *MockBrandRepository_FindAll_Call {
	return &MockBrandRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, skip, take)}
}

func (_c *MockBrandRepository_FindAll_Call) Run(run func(ctx context.Context, skip int, take int)) *MockBrandRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockBrandRepository_FindAll_Call) Return(_a0 []entities.Brand, _a1 int, _a2 error) *MockBrandRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockBrandRepository_FindAll_Call) RunAndReturn(run func(context.Context, int, int) ([]entities.Brand, int, error)) *MockBrandRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockBrandRepository) FindByID(ctx context.Context, id string) (*entities.Brand, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Brand
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Brand, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Brand); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Brand)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBrandRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockBrandRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBrandRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockBrandRepository_FindByID_Call {
	return &MockBrandRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockBrandRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockBrandRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBrandRepository_FindByID_Call) Return(_a0 *entities.Brand, _a1 error) *MockBrandRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBrandRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*entities.Brand, error)) *MockBrandRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBrandRepository creates a new instance of MockBrandRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrandRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrandRepository {
	mock := &MockBrandRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
