// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	services "github.com/lgxju/gogretago/internal/domain/services"
	mock "github.com/stretchr/testify/mock"
)

// MockEmailService is an autogenerated mock type for the EmailService type
type MockEmailService struct {
	mock.Mock
}

type MockEmailService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailService) EXPECT() *MockEmailService_Expecter {
	return &MockEmailService_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: options
func (_m *MockEmailService) Send(options services.SendEmailOptions) error {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(services.SendEmailOptions) error); ok {
		r0 = rf(options)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmailService_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockEmailService_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - options services.SendEmailOptions
func (_e *MockEmailService_Expecter) Send(options interface{}) *MockEmailService_Send_Call {
	return &MockEmailService_Send_Call{Call: _e.mock.On("Send", options)}
}

func (_c *MockEmailService_Send_Call) Run(run func(options services.SendEmailOptions)) *MockEmailService_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(services.SendEmailOptions))
	})
	return _c
}

func (_c *MockEmailService_Send_Call) Return(_a0 error) *MockEmailService_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailService_Send_Call) RunAndReturn(run func(services.SendEmailOptions) error) *MockEmailService_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendWelcomeEmail provides a mock function with given fields: to, firstName
func (_m *MockEmailService) SendWelcomeEmail(to string, firstName string) error {
	ret := _m.Called(to, firstName)

	if len(ret) == 0 {
		panic("no return value specified for SendWelcomeEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(to, firstName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmailService_SendWelcomeEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendWelcomeEmail'
type MockEmailService_SendWelcomeEmail_Call struct {
	*mock.Call
}

// SendWelcomeEmail is a helper method to define mock.On call
//   - to string
//   - firstName string
func (_e *MockEmailService_Expecter) SendWelcomeEmail(to interface{}, firstName interface{}) *MockEmailService_SendWelcomeEmail_Call {
	return &MockEmailService_SendWelcomeEmail_Call{Call: _e.mock.On("SendWelcomeEmail", to, firstName)}
}

func (_c *MockEmailService_SendWelcomeEmail_Call) Run(run func(to string, firstName string)) *MockEmailService_SendWelcomeEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockEmailService_SendWelcomeEmail_Call) Return(_a0 error) *MockEmailService_SendWelcomeEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailService_SendWelcomeEmail_Call) RunAndReturn(run func(string, string) error) *MockEmailService_SendWelcomeEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailService creates a new instance of MockEmailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailService {
	mock := &MockEmailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
