// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/lgxju/gogretago/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockTripRepository is an autogenerated mock type for the TripRepository type
type MockTripRepository struct {
	mock.Mock
}

type MockTripRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTripRepository) EXPECT() *MockTripRepository_Expecter {
	return &MockTripRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, data
func (_m *MockTripRepository) Create(ctx context.Context, data entities.CreateTripData) (*entities.Trip, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.CreateTripData) (*entities.Trip, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.CreateTripData) *entities.Trip); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.CreateTripData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTripRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data entities.CreateTripData
func (_e *MockTripRepository_Expecter) Create(ctx interface{}, data interface{}) *MockTripRepository_Create_Call {
	return &MockTripRepository_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *MockTripRepository_Create_Call) Run(run func(ctx context.Context, data entities.CreateTripData)) *MockTripRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.CreateTripData))
	})
	return _c
}

func (_c *MockTripRepository_Create_Call) Return(_a0 *entities.Trip, _a1 error) *MockTripRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripRepository_Create_Call) RunAndReturn(run func(context.Context, entities.CreateTripData) (*entities.Trip, error)) *MockTripRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockTripRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTripRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTripRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTripRepository_Delete_Call {
	return &MockTripRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTripRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockTripRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTripRepository_Delete_Call) Return(_a0 error) *MockTripRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTripRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockTripRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, skip, take
func (_m *MockTripRepository) FindAll(ctx context.Context, skip int, take int) ([]entities.Trip, int, error) {
	ret := _m.Called(ctx, skip, take)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entities.Trip
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]entities.Trip, int, error)); ok {
		return rf(ctx, skip, take)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []entities.Trip); ok {
		r0 = rf(ctx, skip, take)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, skip, take)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, skip, take)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTripRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockTripRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - skip int
//   - take int
func (_e *MockTripRepository_Expecter) FindAll(ctx interface{}, skip interface{}, take interface{}) *MockTripRepository_FindAll_Call {
	return &MockTripRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, skip, take)}
}

func (_c *MockTripRepository_FindAll_Call) Run(run func(ctx context.Context, skip int, take int)) *MockTripRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTripRepository_FindAll_Call) Return(_a0 []entities.Trip, _a1 int, _a2 error) *MockTripRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTripRepository_FindAll_Call) RunAndReturn(run func(context.Context, int, int) ([]entities.Trip, int, error)) *MockTripRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByFilters provides a mock function with given fields: ctx, filters
func (_m *MockTripRepository) FindByFilters(ctx context.Context, filters entities.TripFilters) ([]entities.Trip, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for FindByFilters")
	}

	var r0 []entities.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.TripFilters) ([]entities.Trip, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.TripFilters) []entities.Trip); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.TripFilters) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripRepository_FindByFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByFilters'
type MockTripRepository_FindByFilters_Call struct {
	*mock.Call
}

// FindByFilters is a helper method to define mock.On call
//   - ctx context.Context
//   - filters entities.TripFilters
func (_e *MockTripRepository_Expecter) FindByFilters(ctx interface{}, filters interface{}) *MockTripRepository_FindByFilters_Call {
	return &MockTripRepository_FindByFilters_Call{Call: _e.mock.On("FindByFilters", ctx, filters)}
}

func (_c *MockTripRepository_FindByFilters_Call) Run(run func(ctx context.Context, filters entities.TripFilters)) *MockTripRepository_FindByFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.TripFilters))
	})
	return _c
}

func (_c *MockTripRepository_FindByFilters_Call) Return(_a0 []entities.Trip, _a1 error) *MockTripRepository_FindByFilters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripRepository_FindByFilters_Call) RunAndReturn(run func(context.Context, entities.TripFilters) ([]entities.Trip, error)) *MockTripRepository_FindByFilters_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockTripRepository) FindByID(ctx context.Context, id string) (*entities.Trip, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Trip, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Trip); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTripRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTripRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockTripRepository_FindByID_Call {
	return &MockTripRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockTripRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockTripRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTripRepository_FindByID_Call) Return(_a0 *entities.Trip, _a1 error) *MockTripRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*entities.Trip, error)) *MockTripRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTripRepository creates a new instance of MockTripRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTripRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTripRepository {
	mock := &MockTripRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
