// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/lgxju/gogretago/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockDriverRepository is an autogenerated mock type for the DriverRepository type
type MockDriverRepository struct {
	mock.Mock
}

type MockDriverRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDriverRepository) EXPECT() *MockDriverRepository_Expecter {
	return &MockDriverRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, data
func (_m *MockDriverRepository) Create(ctx context.Context, data entities.CreateDriverData) (*entities.Driver, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.Driver
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.CreateDriverData) (*entities.Driver, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.CreateDriverData) *entities.Driver); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Driver)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.CreateDriverData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDriverRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDriverRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data entities.CreateDriverData
func (_e *MockDriverRepository_Expecter) Create(ctx interface{}, data interface{}) *MockDriverRepository_Create_Call {
	return &MockDriverRepository_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *MockDriverRepository_Create_Call) Run(run func(ctx context.Context, data entities.CreateDriverData)) *MockDriverRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.CreateDriverData))
	})
	return _c
}

func (_c *MockDriverRepository_Create_Call) Return(_a0 *entities.Driver, _a1 error) *MockDriverRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDriverRepository_Create_Call) RunAndReturn(run func(context.Context, entities.CreateDriverData) (*entities.Driver, error)) *MockDriverRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *MockDriverRepository) FindByUserID(ctx context.Context, userID string) (*entities.Driver, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 *entities.Driver
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Driver, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Driver); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Driver)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDriverRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockDriverRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockDriverRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockDriverRepository_FindByUserID_Call {
	return &MockDriverRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockDriverRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockDriverRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDriverRepository_FindByUserID_Call) Return(_a0 *entities.Driver, _a1 error) *MockDriverRepository_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDriverRepository_FindByUserID_Call) RunAndReturn(run func(context.Context, string) (*entities.Driver, error)) *MockDriverRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserRefID provides a mock function with given fields: ctx, userRefID
func (_m *MockDriverRepository) FindByUserRefID(ctx context.Context, userRefID int64) (*entities.Driver, error) {
	ret := _m.Called(ctx, userRefID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserRefID")
	}

	var r0 *entities.Driver
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entities.Driver, error)); ok {
		return rf(ctx, userRefID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entities.Driver); ok {
		r0 = rf(ctx, userRefID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Driver)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userRefID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDriverRepository_FindByUserRefID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserRefID'
type MockDriverRepository_FindByUserRefID_Call struct {
	*mock.Call
}

// FindByUserRefID is a helper method to define mock.On call
//   - ctx context.Context
//   - userRefID int64
func (_e *MockDriverRepository_Expecter) FindByUserRefID(ctx interface{}, userRefID interface{}) *MockDriverRepository_FindByUserRefID_Call {
	return &MockDriverRepository_FindByUserRefID_Call{Call: _e.mock.On("FindByUserRefID", ctx, userRefID)}
}

func (_c *MockDriverRepository_FindByUserRefID_Call) Run(run func(ctx context.Context, userRefID int64)) *MockDriverRepository_FindByUserRefID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockDriverRepository_FindByUserRefID_Call) Return(_a0 *entities.Driver, _a1 error) *MockDriverRepository_FindByUserRefID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDriverRepository_FindByUserRefID_Call) RunAndReturn(run func(context.Context, int64) (*entities.Driver, error)) *MockDriverRepository_FindByUserRefID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDriverRepository creates a new instance of MockDriverRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDriverRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDriverRepository {
	mock := &MockDriverRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
