// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/lgxju/gogretago/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Anonymize provides a mock function with given fields: ctx, id
func (_m *MockUserRepository) Anonymize(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Anonymize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Anonymize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Anonymize'
type MockUserRepository_Anonymize_Call struct {
	*mock.Call
}

// Anonymize is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepository_Expecter) Anonymize(ctx interface{}, id interface{}) *MockUserRepository_Anonymize_Call {
	return &MockUserRepository_Anonymize_Call{Call: _e.mock.On("Anonymize", ctx, id)}
}

func (_c *MockUserRepository_Anonymize_Call) Run(run func(ctx context.Context, id string)) *MockUserRepository_Anonymize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_Anonymize_Call) Return(_a0 error) *MockUserRepository_Anonymize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Anonymize_Call) RunAndReturn(run func(context.Context, string) error) *MockUserRepository_Anonymize_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockUserRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockUserRepository_Delete_Call {
	return &MockUserRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUserRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockUserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_Delete_Call) Return(_a0 error) *MockUserRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockUserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockUserRepository) FindAll(ctx context.Context) ([]entities.PublicUser, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entities.PublicUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.PublicUser, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.PublicUser); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.PublicUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockUserRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserRepository_Expecter) FindAll(ctx interface{}) *MockUserRepository_FindAll_Call {
	return &MockUserRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockUserRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockUserRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUserRepository_FindAll_Call) Return(_a0 []entities.PublicUser, _a1 error) *MockUserRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]entities.PublicUser, error)) *MockUserRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByAuthRefID provides a mock function with given fields: ctx, authRefID
func (_m *MockUserRepository) FindByAuthRefID(ctx context.Context, authRefID int64) (*entities.PublicUser, error) {
	ret := _m.Called(ctx, authRefID)

	if len(ret) == 0 {
		panic("no return value specified for FindByAuthRefID")
	}

	var r0 *entities.PublicUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entities.PublicUser, error)); ok {
		return rf(ctx, authRefID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entities.PublicUser); ok {
		r0 = rf(ctx, authRefID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.PublicUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, authRefID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindByAuthRefID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAuthRefID'
type MockUserRepository_FindByAuthRefID_Call struct {
	*mock.Call
}

// FindByAuthRefID is a helper method to define mock.On call
//   - ctx context.Context
//   - authRefID int64
func (_e *MockUserRepository_Expecter) FindByAuthRefID(ctx interface{}, authRefID interface{}) *MockUserRepository_FindByAuthRefID_Call {
	return &MockUserRepository_FindByAuthRefID_Call{Call: _e.mock.On("FindByAuthRefID", ctx, authRefID)}
}

func (_c *MockUserRepository_FindByAuthRefID_Call) Run(run func(ctx context.Context, authRefID int64)) *MockUserRepository_FindByAuthRefID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockUserRepository_FindByAuthRefID_Call) Return(_a0 *entities.PublicUser, _a1 error) *MockUserRepository_FindByAuthRefID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindByAuthRefID_Call) RunAndReturn(run func(context.Context, int64) (*entities.PublicUser, error)) *MockUserRepository_FindByAuthRefID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockUserRepository) FindByID(ctx context.Context, id string) (*entities.PublicUser, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.PublicUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.PublicUser, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.PublicUser); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.PublicUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockUserRepository_FindByID_Call {
	return &MockUserRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockUserRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockUserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_FindByID_Call) Return(_a0 *entities.PublicUser, _a1 error) *MockUserRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*entities.PublicUser, error)) *MockUserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, data
func (_m *MockUserRepository) Update(ctx context.Context, id string, data entities.UpdateUserData) (*entities.PublicUser, error) {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entities.PublicUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.UpdateUserData) (*entities.PublicUser, error)); ok {
		return rf(ctx, id, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.UpdateUserData) *entities.PublicUser); ok {
		r0 = rf(ctx, id, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.PublicUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, entities.UpdateUserData) error); ok {
		r1 = rf(ctx, id, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - data entities.UpdateUserData
func (_e *MockUserRepository_Expecter) Update(ctx interface{}, id interface{}, data interface{}) *MockUserRepository_Update_Call {
	return &MockUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, data)}
}

func (_c *MockUserRepository_Update_Call) Run(run func(ctx context.Context, id string, data entities.UpdateUserData)) *MockUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entities.UpdateUserData))
	})
	return _c
}

func (_c *MockUserRepository_Update_Call) Return(_a0 *entities.PublicUser, _a1 error) *MockUserRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_Update_Call) RunAndReturn(run func(context.Context, string, entities.UpdateUserData) (*entities.PublicUser, error)) *MockUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
