// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	services "github.com/lgxju/gogretago/internal/domain/services"
	mock "github.com/stretchr/testify/mock"
)

// MockJwtService is an autogenerated mock type for the JwtService type
type MockJwtService struct {
	mock.Mock
}

type MockJwtService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwtService) EXPECT() *MockJwtService_Expecter {
	return &MockJwtService_Expecter{mock: &_m.Mock}
}

// Sign provides a mock function with given fields: payload
func (_m *MockJwtService) Sign(payload services.JwtPayload) (string, error) {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(services.JwtPayload) (string, error)); ok {
		return rf(payload)
	}
	if rf, ok := ret.Get(0).(func(services.JwtPayload) string); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(services.JwtPayload) error); ok {
		r1 = rf(payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJwtService_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockJwtService_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - payload services.JwtPayload
func (_e *MockJwtService_Expecter) Sign(payload interface{}) *MockJwtService_Sign_Call {
	return &MockJwtService_Sign_Call{Call: _e.mock.On("Sign", payload)}
}

func (_c *MockJwtService_Sign_Call) Run(run func(payload services.JwtPayload)) *MockJwtService_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(services.JwtPayload))
	})
	return _c
}

func (_c *MockJwtService_Sign_Call) Return(_a0 string, _a1 error) *MockJwtService_Sign_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJwtService_Sign_Call) RunAndReturn(run func(services.JwtPayload) (string, error)) *MockJwtService_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: token
func (_m *MockJwtService) Verify(token string) (*services.JwtPayload, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *services.JwtPayload
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*services.JwtPayload, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *services.JwtPayload); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.JwtPayload)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJwtService_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockJwtService_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - token string
func (_e *MockJwtService_Expecter) Verify(token interface{}) *MockJwtService_Verify_Call {
	return &MockJwtService_Verify_Call{Call: _e.mock.On("Verify", token)}
}

func (_c *MockJwtService_Verify_Call) Run(run func(token string)) *MockJwtService_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockJwtService_Verify_Call) Return(_a0 *services.JwtPayload, _a1 error) *MockJwtService_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJwtService_Verify_Call) RunAndReturn(run func(string) (*services.JwtPayload, error)) *MockJwtService_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwtService creates a new instance of MockJwtService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwtService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwtService {
	mock := &MockJwtService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
