// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/lgxju/gogretago/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockAuthRepository is an autogenerated mock type for the AuthRepository type
type MockAuthRepository struct {
	mock.Mock
}

type MockAuthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepository) EXPECT() *MockAuthRepository_Expecter {
	return &MockAuthRepository_Expecter{mock: &_m.Mock}
}

// CreateWithUser provides a mock function with given fields: ctx, authData, userData
func (_m *MockAuthRepository) CreateWithUser(ctx context.Context, authData entities.CreateAuthData, userData entities.CreateUserData) (*entities.Auth, *entities.PublicUser, error) {
	ret := _m.Called(ctx, authData, userData)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithUser")
	}

	var r0 *entities.Auth
	var r1 *entities.PublicUser
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.CreateAuthData, entities.CreateUserData) (*entities.Auth, *entities.PublicUser, error)); ok {
		return rf(ctx, authData, userData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.CreateAuthData, entities.CreateUserData) *entities.Auth); ok {
		r0 = rf(ctx, authData, userData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Auth)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.CreateAuthData, entities.CreateUserData) *entities.PublicUser); ok {
		r1 = rf(ctx, authData, userData)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.PublicUser)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, entities.CreateAuthData, entities.CreateUserData) error); ok {
		r2 = rf(ctx, authData, userData)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuthRepository_CreateWithUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithUser'
type MockAuthRepository_CreateWithUser_Call struct {
	*mock.Call
}

// CreateWithUser is a helper method to define mock.On call
//   - ctx context.Context
//   - authData entities.CreateAuthData
//   - userData entities.CreateUserData
func (_e *MockAuthRepository_Expecter) CreateWithUser(ctx interface{}, authData interface{}, userData interface{}) *MockAuthRepository_CreateWithUser_Call {
	return &MockAuthRepository_CreateWithUser_Call{Call: _e.mock.On("CreateWithUser", ctx, authData, userData)}
}

func (_c *MockAuthRepository_CreateWithUser_Call) Run(run func(ctx context.Context, authData entities.CreateAuthData, userData entities.CreateUserData)) *MockAuthRepository_CreateWithUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.CreateAuthData), args[2].(entities.CreateUserData))
	})
	return _c
}

func (_c *MockAuthRepository_CreateWithUser_Call) Return(_a0 *entities.Auth, _a1 *entities.PublicUser, _a2 error) *MockAuthRepository_CreateWithUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuthRepository_CreateWithUser_Call) RunAndReturn(run func(context.Context, entities.CreateAuthData, entities.CreateUserData) (*entities.Auth, *entities.PublicUser, error)) *MockAuthRepository_CreateWithUser_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByEmail provides a mock function with given fields: ctx, email
func (_m *MockAuthRepository) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByEmail")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthRepository_ExistsByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByEmail'
type MockAuthRepository_ExistsByEmail_Call struct {
	*mock.Call
}

// ExistsByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthRepository_Expecter) ExistsByEmail(ctx interface{}, email interface{}) *MockAuthRepository_ExistsByEmail_Call {
	return &MockAuthRepository_ExistsByEmail_Call{Call: _e.mock.On("ExistsByEmail", ctx, email)}
}

func (_c *MockAuthRepository_ExistsByEmail_Call) Run(run func(ctx context.Context, email string)) *MockAuthRepository_ExistsByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthRepository_ExistsByEmail_Call) Return(_a0 bool, _a1 error) *MockAuthRepository_ExistsByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthRepository_ExistsByEmail_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockAuthRepository_ExistsByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *MockAuthRepository) FindByEmail(ctx context.Context, email string) (*entities.Auth, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *entities.Auth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Auth, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Auth); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Auth)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockAuthRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthRepository_Expecter) FindByEmail(ctx interface{}, email interface{}) *MockAuthRepository_FindByEmail_Call {
	return &MockAuthRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockAuthRepository_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockAuthRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthRepository_FindByEmail_Call) Return(_a0 *entities.Auth, _a1 error) *MockAuthRepository_FindByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthRepository_FindByEmail_Call) RunAndReturn(run func(context.Context, string) (*entities.Auth, error)) *MockAuthRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function with given fields: ctx, refID, role
func (_m *MockAuthRepository) UpdateRole(ctx context.Context, refID int64, role string) error {
	ret := _m.Called(ctx, refID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, refID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthRepository_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type MockAuthRepository_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - refID int64
//   - role string
func (_e *MockAuthRepository_Expecter) UpdateRole(ctx interface{}, refID interface{}, role interface{}) *MockAuthRepository_UpdateRole_Call {
	return &MockAuthRepository_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, refID, role)}
}

func (_c *MockAuthRepository_UpdateRole_Call) Run(run func(ctx context.Context, refID int64, role string)) *MockAuthRepository_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockAuthRepository_UpdateRole_Call) Return(_a0 error) *MockAuthRepository_UpdateRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthRepository_UpdateRole_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockAuthRepository_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthRepository creates a new instance of MockAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepository {
	mock := &MockAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
