version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - revive
    - misspell
    - unconvert
    - predeclared
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    paths:
      - internal/mocks
